name: Dev Deployment

on:
  push:
    branches:
      - dev
      - feature/*

permissions:
  contents: read
  id-token: write
  actions: write

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests with vitest
        run: npm run coverage

      - name: Upload test coverage as artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./coverage

      - name: Check if coverage directory exists
        run: |
          echo "Listing coverage files:"
          ls ./coverage
          if [ ! -d ./coverage ]; then
            echo "Coverage directory not found!"
            exit 1
          fi
          echo "Coverage directory found"

      - name: Check test coverage
        run: |
          COVERAGE=$(cat ./coverage/coverage-summary.json | jq .total.lines.pct)
          echo "Test coverage is ${COVERAGE}%"
          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
            echo "Test coverage is below 90%, but proceeding with deployment."
          fi

      - name: Build the project
        run: npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync ./dist s3://mambyly-logistics-frontend-dev --delete
