name: Dev Deployment

on:
  push:
    branches:
      - dev
      - feature/*

permissions:
  contents: read
  id-token: write
  actions: write

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests with vitest
        run: npm run coverage

      # Debug: Listing contents of coverage directory to check if the report is generated correctly
      - name: Check contents of coverage directory
        run: |
          echo "Listing contents of coverage directory:"
          ls -R ./coverage

      # Upload the coverage report
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

      # Debug: Check if coverage directory exists and has the required report
      - name: Check if coverage directory exists
        run: |
          echo "Listing coverage files:"
          ls ./coverage
          if [ ! -d ./coverage ]; then
            echo "Coverage directory not found!"
            exit 1
          fi
          if [ ! -f ./coverage/coverage-summary.json ]; then
            echo "Coverage report not found!"
            exit 1
          fi
          echo "Coverage report found"

      # Check test coverage and proceed with deployment even if coverage is below threshold
      - name: Check test coverage
        run: |
          COVERAGE=$(cat ./coverage/coverage-summary.json | jq .total.lines.pct)
          echo "Test coverage is ${COVERAGE}%"
          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
            echo "Test coverage is below 90%, but proceeding with deployment."
          fi

      # Build the project if tests pass
      - name: Build the project
        run: npm run build

      # Debug: Check if build folder (dist) is ready before deploying
      - name: Check build directory before deploy
        run: |
          echo "Listing contents of build (dist) directory"
          ls -R ./dist
          if [ ! -d ./dist ]; then
            echo "Build directory not found!"
            exit 1
          fi
          echo "Build directory found"

      # Deploy to S3
      - name: Deploy to S3
        run: |
          echo "Deploying to S3 bucket"
          aws s3 sync ./dist s3://mambyly-logistics-frontend-dev --delete
